### ISSUE TITLE
Pathing / config bugs

### ISSUE THREAD

**Issue by OR13** [csuwildcat/spec-up#4]
I have tried to use this a few times, and I'm finding it very frustrating :)

There should be a json file in the root of a spec repo called `spec.json`.... if should allow you to point to a directory which github will serve (`.` for master / gh-pages branch, `./docs` for master docs).

the "spec-up" files should get copied there... not the root directory.

If i can't configure where those files go, I can't make the spec render correctly.

**Comment by csuwildcat** [comment]
The thing you are lamenting I did for a reason: you can have many different specs all over your repo at n-depth in different directories and the tool will automatically find them, detect them, and connect the single set of spec-up files/assets to the generated output HTML via the correct paths paths relative to the assets. What you're essentially asking me to do is to change this so that if someone had multiple specs in a repo, I would copy the same files multiple times to different directory locations. I found that to be wasteful, so I tried to eliminate it. I suppose I could do this, but felt it was not optimal.

**Comment by OR13** [comment]
"spec_directory": "./docs",

./docs/spec.md

Should result in:

./docs/spec-up/*
./docs/spec-up/index.html

**Comment by csuwildcat** [comment]
These changes were made and now work to do as described.
